[[DataProduct-API]]
== DataProduct API

[[데이터-리스트-페이징-조회]]
=== DataProduct 전체 페이징 조회
operation::data-product-controller-test/find-data-products[snippets='http-request,request-fields,path-parameters,http-response,response-fields']

[[선택한-카테고리에-해당하는-데이터-상품-조회]]
=== DataProduct 카테고리별 조회
operation::data-product-controller-test/find-category-data-products[snippets='http-request,request-fields,path-parameters,http-response,response-fields']

[[데이터-상품-구매횟수-TOP3-조회]]
=== DataProduct 상품 구매 TOP3 조회
operation::data-product-controller-test/find-category-data-products-top3[snippets='http-request,request-fields,path-parameters,http-response,response-fields']

[[데이터-상품-상세-조회]]
=== DataProduct 데이터 상품 상세 조회
operation::data-product-controller-test/find-data-product[snippets='http-request,request-fields,path-parameters,http-response,response-fields']

[[유저가-보유한-데이터-ZIP-업로드]]
=== DataProduct Zip 업로드
operation::data-product-controller-test/sale-data-products-zip[snippets='http-request,request-fields,path-parameters,http-response,response-fields']

[[유저가-보유한-예시-이미지-업로드]]
=== DataProduct ExampleImages 업로드
operation::data-product-controller-test/sale-data-products-images[snippets='http-request,request-fields,path-parameters,http-response,response-fields']

[[유저가-판매할-데이터-요청-폼-작성]]
=== DataProduct RequestForm 작성
operation::data-product-controller-test/sale-data-products-form[snippets='http-request,request-fields,path-parameters,http-response,response-fields']

[[유저가-보유한-데이터-판매]]
=== DataProduct 판매
operation::data-product-controller-test/sale-data-products[snippets='http-request,request-fields,path-parameters,http-response,response-fields']

